src/Entity/Objekt.php
<?php

namespace App\Entity;

use App\Repository\ObjektRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ObjektRepository::class)]
class Objekt
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'objekt', targetEntity: User::class)]
    private Collection $users;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $ort = null;

    #[ORM\Column(length: 255)]
    private ?string $plz = null;

    #[ORM\Column(length: 255)]
    private ?string $main_mail = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;
    

    #[ORM\Column(length: 255)]
    private ?string $telefon = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fax = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bestellung_mail = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fibi_mail = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ust_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Handelsregister = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Amtsgericht = null;

    #[ORM\ManyToOne(inversedBy: 'objekts')]
    private ?Company $company = null;

    #[ORM\OneToMany(mappedBy: 'objekt', targetEntity: RentItems::class)]
    private Collection $rentItems;
    #[ORM\ManyToOne(inversedBy: 'objekt')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ObjektCategories $categories = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bild = null;

    #[ORM\OneToMany(mappedBy: 'objekt', targetEntity: OpeningTime::class)]
    private Collection $openingTimes;

    #[ORM\OneToMany(mappedBy: 'objket', targetEntity: SpecialOpeningTime::class)]
    private Collection $specialOpeningTimes;

    #[ORM\Column(nullable: true)]
    private ?int $staytime = null;

    #[ORM\OneToMany(mappedBy: 'objekt', targetEntity: Area::class, orphanRemoval: true)]
    private Collection $areas;

    #[ORM\OneToMany(mappedBy: 'objekt', targetEntity: Vertrag::class, orphanRemoval: true)]
    private Collection $vertrags;

    #[ORM\OneToMany(mappedBy: 'Objket', targetEntity: Dienstplan::class, orphanRemoval: true)]
    private Collection $dienstplans;

    #[ORM\OneToMany(mappedBy: 'objekt', targetEntity: Arbeitsbereiche::class)]
    private Collection $arbeitsbereiche;

    #[ORM\OneToMany(mappedBy: 'objekt', targetEntity: ItemCategories::class, orphanRemoval: true)]
    private Collection $itemCategories;

  
    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->rentItems = new ArrayCollection();
        $this->openingTimes = new ArrayCollection();
        $this->specialOpeningTimes = new ArrayCollection();
        $this->areas = new ArrayCollection();
        $this->vertrags = new ArrayCollection();
        $this->dienstplans = new ArrayCollection();
        $this->arbeitsbereiche = new ArrayCollection();
        $this->itemCategories = new ArrayCollection();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setObjekt($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getObjekt() === $this) {
                $user->setObjekt(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->name;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getOrt(): ?string
    {
        return $this->ort;
    }

    public function setOrt(string $ort): self
    {
        $this->ort = $ort;

        return $this;
    }

    public function getPlz(): ?string
    {
        return $this->plz;
    }

    public function setPlz(string $plz): self
    {
        $this->plz = $plz;

        return $this;
    }

    public function getMainMail(): ?string
    {
        return $this->main_mail;
    }

    public function setMainMail(string $main_mail): self
    {
        $this->main_mail = $main_mail;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getTelefon(): ?string
    {
        return $this->telefon;
    }

    public function setTelefon(string $telefon): self
    {
        $this->telefon = $telefon;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getBestellungMail(): ?string
    {
        return $this->bestellung_mail;
    }

    public function setBestellungMail(?string $bestellung_mail): self
    {
        $this->bestellung_mail = $bestellung_mail;

        return $this;
    }

    public function getFibiMail(): ?string
    {
        return $this->fibi_mail;
    }

    public function setFibiMail(?string $fibi_mail): self
    {
        $this->fibi_mail = $fibi_mail;

        return $this;
    }

    public function getUstId(): ?string
    {
        return $this->ust_id;
    }

    public function setUstId(?string $ust_id): self
    {
        $this->ust_id = $ust_id;

        return $this;
    }

    public function getHandelsregister(): ?string
    {
        return $this->Handelsregister;
    }

    public function setHandelsregister(?string $Handelsregister): self
    {
        $this->Handelsregister = $Handelsregister;

        return $this;
    }

    public function getAmtsgericht(): ?string
    {
        return $this->Amtsgericht;
    }

    public function setAmtsgericht(?string $Amtsgericht): self
    {
        $this->Amtsgericht = $Amtsgericht;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection<int, RentItems>
     */
    public function getRentItems(): Collection
    {
        return $this->rentItems;
    }

    public function addRentItem(RentItems $rentItem): self
    {
        if (!$this->rentItems->contains($rentItem)) {
            $this->rentItems->add($rentItem);
            $rentItem->setObjekt($this);
        }

        return $this;
    }

    public function removeRentItem(RentItems $rentItem): self
    {
        if ($this->rentItems->removeElement($rentItem)) {
            // set the owning side to null (unless already changed)
            if ($rentItem->getObjekt() === $this) {
                $rentItem->setObjekt(null);
            }
        }

        return $this;
    }

    public function getCategories(): ?ObjektCategories
    {
        return $this->categories;
    }

    public function setCategories(?ObjektCategories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getBild(): ?string
    {
        return $this->bild;
    }

    public function setBild(?string $bild): self
    {
        $this->bild = $bild;

        return $this;
    }

    /**
     * @return Collection<int, OpeningTime>
     */
    public function getOpeningTimes(): Collection
    {
        return $this->openingTimes;
    }

    public function addOpeningTime(OpeningTime $openingTime): self
    {
        if (!$this->openingTimes->contains($openingTime)) {
            $this->openingTimes->add($openingTime);
            $openingTime->setObjekt($this);
        }

        return $this;
    }

    public function removeOpeningTime(OpeningTime $openingTime): self
    {
        if ($this->openingTimes->removeElement($openingTime)) {
            // set the owning side to null (unless already changed)
            if ($openingTime->getObjekt() === $this) {
                $openingTime->setObjekt(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, SpecialOpeningTime>
     */
    public function getSpecialOpeningTimes(): Collection
    {
        return $this->specialOpeningTimes;
    }

    public function addSpecialOpeningTime(SpecialOpeningTime $specialOpeningTime): self
    {
        if (!$this->specialOpeningTimes->contains($specialOpeningTime)) {
            $this->specialOpeningTimes->add($specialOpeningTime);
            $specialOpeningTime->setObjket($this);
        }

        return $this;
    }

    public function removeSpecialOpeningTime(SpecialOpeningTime $specialOpeningTime): self
    {
        if ($this->specialOpeningTimes->removeElement($specialOpeningTime)) {
            // set the owning side to null (unless already changed)
            if ($specialOpeningTime->getObjket() === $this) {

src/Form/ObjektType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Objekt;
use App\Entity\ObjektCategories;
use App\Entity\User;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class ObjektType extends AbstractType

{   private $doctrine;
    private $tokenStorage;
    public function __construct(TokenStorageInterface $tokenStorage,ManagerRegistry $doctrine)
    {
        $this->tokenStorage = $tokenStorage;
        $this->doctrine = $doctrine;
    }

    public function buildForm( FormBuilderInterface $builder, array $options): void
    {
        $user = $this->tokenStorage->getToken()->getUser();
        //companys des benutzers ermitteln -admin einer Company
        $companies = $this->doctrine->getRepository(Company::class)->findBy(['onjekt_admin' => $user]);

        $userobjekt = $this->doctrine->getRepository(User::class)->find( $user); 
        $objekt = $userobjekt->getObjekt();
        foreach ($companies as $company) {
            $choices[$company->getName()] = $company;
        }
        
    
        $builder
            ->add('name',null,[
                'label' => 'Bezeichnung *',
            ])
            ->add('adresse',null,[
                'label' => 'Straße & Hausnummer *',
            ])
            ->add('ort',null,[
                'label' => 'Ort *',
            ])
           
            ->add('plz',null,[
                'label' => 'Postleitzahl *',
            ])
            ->add('main_mail',null,[
                'label' => 'Emailadresse *',
            ])
            
            ->add('telefon',null,[
                'label' => 'Telefonnummer *',
            ])
            ->add('website', null, [
                'required' => false,
            ]);
            
            if($objekt and $objekt->getBild()){
                $builder->add('bild', FileType::class,array(
                    'data_class' => null,
                     'required' => false,
                     'label' => 'Objektbild',
                   'data' => $objekt->getBild(), // Setze den Wert des Feldes auf den Namen des vorhandenen Bildes
                ));
            }
            else{
                $builder->add('bild', FileType::class,array(
                    'data_class' => null,
                     'required' => false,
                     'label' => 'Objektbild',
                     
    
                    
                ));
            }
            $builder->add('fax', null, [
                'required' => false,
                'label' => 'Faxnummer',
            ])
            ->add('bestellung_mail', null, [
                'required' => false,
                'label' => 'Mail Warenwirtschaft',
            ])
            ->add('fibi_mail', null, [
                'required' => false,
                'label' => 'Mail Finanzbuchhaltung',
            ])
            ->add('ust_id', null, [
                'required' => false,
                'label' => 'Ust ID',
            ])
            ->add('Handelsregister', null, [
                'required' => false,
            ])
            ->add('Amtsgericht', null, [
                'required' => false,
            ])
            ->add('company', ChoiceType::class, [
                'choices' => $choices,
                'expanded' => true,
                'multiple' => false,
                'label' => 'Unternehmen  *',
            ])
            ->add('categories', EntityType::class, [
                'class' => ObjektCategories::class,
                'label' => 'Kategorie auswählen  *',
            ])
        ;
    }
    

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Objekt::class,
        ]);
    }
}

templates/objekt/_delete_form.html.twig
<form method="post" action="{{ path('app_objekt_delete', {'id': objekt.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input class="btn w-100 btn-info" type="hidden" name="_token" value="{{ csrf_token('delete' ~ objekt.id) }}">
    <button class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Delete</button>
</form>

templates/objekt/_form.html.twig
<style>
#objekt div{ display:grid; margin:10px 0px;}

</style>


{{ form_start(form) }}
    
   {{ form_widget(form) }}
   <button class="btn w-100 btn-info" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">{{ button_label|default('Save') }}</button>
    
{{ form_end(form) }}

templates/objekt/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Objekt{% endblock %}

{% block body %}
<div class="container">
    <h1>{{objekt.name}} bearbeiten</h1>
    {{ include('objekt/_form.html.twig', {'button_label': 'Update'}) }}
</div>
{% endblock %}

templates/objekt/editForm.html.twig
 {% block javascripts %} 
   
       
   
   <script language = "javascript">  
      $(document).ready(function(){  
         //  var id =  $(this).attr('id');
        $(".edit_form").submit(function(e) {
                    e.preventDefault(); // avoid to execute the actual submit of the form.
                    var form = $(this);
                      $.ajax({
                        type: "POST",
                        url: "{{path('ajax_ItemUpdate')}}",
                        data: form.serialize(), // serializes the form's elements.
                        success: function(data)
                        {

                          $( "#dialog" ).dialog( "close" ); 
                          location.reload();
                        },
                        error : function(xhr, textStatus, errorThrown) {  
                          
                          alert('Ajax request failed sss.');
                          
                        }
                    });
             
        });   
         



      });  
        
   </script>  
{% endblock %} 

          
{% block body %} 


{{ form_start(form, {'attr': {'class': 'edit_form'} }) }}

   {{ form_widget(form.id, {'attr': {'style': 'display:none;'} })}}
 
    

{{ form_end(form) }}

{% endblock %}

templates/objekt/editFormArea.html.twig
 {% block javascripts %} 

   <script language = "javascript">  
      
   </script>  
{% endblock %} 

          
{% block body %} 
{{ form_start(form, {'attr': {'class': 'edit_form'}, 'action': path('ajax_AreaEditSave', {'id': area.id})}) }}
{{ form_end(form) }}
<a class="btn btn-danger w-100"  href="{{ path('area_delete', {'id': area.id})}}"> <i class="fas fa-trash"></i></a>

{% endblock %}

templates/objekt/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{objekts[0].company.name}}
{% endblock %}

{% block body %}
	<!-- Modal -->
	<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel"></h5>
					<button type="button" id="modalCloseBtn" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="closeModal()"></button>
				</div>
				<div
					class="modal-body" id="modal-body"><!-- Hier wird der Inhalt von app_user_contrect geladen -->
				</div>
			</div>
		</div>
	</div>

	<div class='d-flex'>
		<a class=" text-info " href="{{ path('app_company_edit', {'id': objekts[0].company.id}) }}">
			<h1>{{objekts[0].company.name }}</h1>
		</a>

		<a class="" href="{{ path('app_objekt_new') }}">
			<i class="fas fa-plus"></i>
		</a>
	</div>
	<div class="container">
		{% for objekt in objekts %}
			<div class="card object-setting">
				{% if objekt.bild is null %}

					<i class="fas fa-image"></i>
				{% else %}
					{% if is_granted('IS_AUTHENTICATED_FULLY') %}

						<img class="card-img-top" style='max-height: 250px; object-fit: cover;position:relative' src="{{ asset('images/' ~ objekt.bild) }}" alt="Objekt Foto">
						<!--<button onclick="delateImage('{{ objekt.bild }}')" type="button" style="position: absolute; right: 0; margin: 10px; border: none; background: none;" class="fas fa-trash text-danger"></button>-->
					{% else %}
						<i class="fas fa-image"></i>
					{% endif %}
				{% endif %}
				<div class='infos'>
					<h5>{{ objekt.categories }}</h5>
					<div class='d-flex'>
						<h4 class="card-title">{{ objekt.name }}</h4>

					</div>
					<p class="card-text">{{ objekt.adresse }},{{ objekt.plz }}
						{{ objekt.ort }}
						<br>Telefon:
						{{ objekt.telefon }}
						<br>Email:
						{{ objekt.mainMail }}</p>
				</div>
				<div class="card-body p-0 d-flex justify-content-around flex-wrap control-wrapper mt-2" >


					<div class="container d-flex justify-content-around flex-wrap  control-panel">
						<a href="{{ path('app_objekt_edit', {'id': objekt.id}) }}">
							<div class="card  m-1 text-center">
								<div class="card-header glass-effect">
									Einstellung
								</div>
								<div class='card-body border-top'>
									<i class="object-icon fa fa-cog " ></i>
								</div>
							</div>
						</a>

						<a href="{{ path('app_objekt_opening', {'id': objekt.id}) }}">
							<div class="card  m-1 text-center">
								<div class="card-header glass-effect">
									Öffnungszeiten
								</div>
								<div class='card-body border-top'>
									<i class="object-icon fa fa-clock " ></i>
								</div>
							</div>
						</a>

						<a href="{{ path('app_item_categories_index', {'objectId':objekt.id }) }}">
							<div class="card  m-1 text-center">
								<div class="card-header glass-effect">
									Kategorien
								</div>
								<div class='card-body border-top'>
									<i class="object-icon fa fa-archive " ></i>
								</div>
							</div>
						</a>

						{% if objekt.categories == 'Restaurant' %}
							<a href="{{ path('rent_items', {'id': objekt.id}) }}">
								<div class="card  m-1 text-center">
									<div class="card-header glass-effect">
										Reviere & Tische
									</div>
									<div class='card-body border-top'>
										<i class="object-icon fa fa-cutlery " ></i>
									</div>
								</div>
							</a>

						{% else %}
							<a href="{{ path('rent_items', {'id': objekt.id}) }}">
								<div class="card  m-1 text-center">
									<div class="card-header glass-effect">
										Etagen & Zimmer
									</div>
									<div class='card-body border-top'>
										<i class="object-icon fa fa-bed " ></i>
									</div>
								</div>
							</a>

						{% endif %}
						<a href="#" onclick="openModal_objekt_dienstplan({{ objekt.id }})">
							<div class="card  m-1 text-center">
								<div class="card-header glass-effect">
									Dienstplan
								</div>
								<div class='card-body border-top'>
									<i class="object-icon fa fa-calendar" aria-hidden="true" ></i>
								</div>
							</div>
						</a>

						<a href="#" onclick="openModal_objekt_vertrag({{ objekt.id }})">
							<div class="card  m-1 text-center">
								<div class="card-header glass-effect">
									Verträg & Vereinbarungen
								</div>
								<div class='card-body border-top'>
									<i class="object-icon fa fa-file" ></i>
								</div>
							</div>
						</a>


					</div>
				</div>


			</div>
		{% endfor %}
	</div>
{% endblock %}
{% block javascripts %}
	{{ parent() }}
 <script src="{{ asset('js/modal.js') }}"></script>
	 <script>
				
				    
				    const sa = document.getElementById('datalte_image');
				    function delateImage(bild){
				       
				        DelateObjektImage(bild);
				        
				    } 
				    
				
				
				    </script>


{% endblock %}

templates/objekt/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Standort{% endblock %}

{% block body %}
    <h1>Erstelle ein Standort</h1>

    {{ include('objekt/_form.html.twig') }}

{% endblock %}

templates/objekt/newForm.html.twig
 {% block javascripts %} 
   
       
   
   <script language = "javascript">  
      $(document).ready(function(){  
        
        
                
                $(".edit_form").submit(function(e) {
                    e.preventDefault(); // avoid to execute the actual submit of the form.
                    var form = $(this);
                  
                    $.ajax({
                        type: "POST",
                        url: "{{path('ajax_ItemNewSave')}}",
                        data: form.serialize(), // serializes the form's elements.
                        success: function(data)
                        {

                          $( "#dialog" ).dialog( "close" ); 
                          location.reload();
                         
                        },
                        error : function(xhr, textStatus, errorThrown) {  
                          
                          alert('Ajax request failed new form.');
                          
                        }
                    });
             
                });
             
      });  
        
   </script>  
{% endblock %} 

          
{% block body %} 


{{ form_start(form, {'attr': {'class': 'edit_form'} }) }}
   
 <p class='d-none'>{{ form_widget(form.id) }}</p>
    

{{ form_end(form) }}

{% endblock %}

templates/objekt/newFormArea.html.twig
 {% block javascripts %} 
   
       
   
   <script language = "javascript">  
      $(document).ready(function(){  
         //  var id =  $(this).attr('id');
        
        /*        
                $(".edit_form").submit(function(e) {
                    e.preventDefault(); // avoid to execute the actual submit of the form.
                    var form = $(this);
                  
                    $.ajax({
                        type: "POST",
                        url: "{{path('ajax_AreaNewSave')}}",
                        data: form.serialize(), // serializes the form's elements.
                        success: function(data)
                        {
                          $( "#dialog" ).dialog( "close" ); 
                          location.reload();
                        },
                        error : function(xhr, textStatus, errorThrown) {  
                          alert('Ajax request failed new form.');
                        }
                    });
             
                });
             
         */    
            
      });  
        
   </script>  
{% endblock %} 

          
{% block body %} 


{{ form_start(form, {'attr': {'class': 'edit_form'}, 'action': path('ajax_AreaNewSave')}) }}
   
 
    

{{ form_end(form) }}

{% endblock %}

templates/objekt/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Objekt{% endblock %}

{% block body %}
<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" id="modalCloseBtn" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="closeModal()"></button>
            </div>
            <div class="modal-body" id="modal-body">
                <!-- Hier wird der Inhalt von app_user_contrect geladen -->
            </div>
        </div>
    </div>
</div>
    <div class="container">
    <div class="row  gx-2">
        
    
        
        <div class="col p-3 col-sm-6 col-12">
            <div class="card">
                <div class="card-body">
                    <blockquote class="blockquote">
                        <h1>{{ objekt.name }}</h1>
                        <img  src="{{asset('images/' ~ objekt.bild)}}" class=" img-fluid" >
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="col p-3 col-sm-6 col-12">
            <div class="card">
                <div class="card-body">

                <ul class="nav nav-tabs">
                    <li class="nav-item w-100 text-center">
                        <a class="nav-link nav-link-user  " href="{{ path('app_objekt_opening', {'id': objekt.id}) }}">Opening Times</a>
                    </li>
                     <li class="nav-item w-100 text-center">
                        <a class="nav-link nav-link-user  " href="{{ path('rent_items', {'id': objekt.id}) }}">Areas &amp Itams</a>
                    </li>
                     <li class="nav-item w-100 text-center">
                        <a class="nav-link nav-link-user  " href="#" onclick="openModal_objekt_dienstplan({{ objekt.id }})">Dienstplan</a>
                    </li>
                     <li class="nav-item w-100 text-center">
                        <a class="nav-link nav-link-user  " href="#" onclick="openModal_objekt_vertrag()">vertrag</a>
                    </li>
                </ul>


                    
                </div>
            </div> 
        </div>
        <div class="col p-3 col-sm-6 col-12 w-100">
            <div class="card">
                <div class="card-body">
                    <blockquote class="blockquote">
        
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Id</th>
                                    <td>{{ objekt.id }}</td>
                                </tr>
                                <tr>
                                    <th>Name</th>
                                    <td>{{ objekt.name }}</td>
                                </tr>
                                <tr>
                                    <th>Adresse</th>
                                    <td>{{ objekt.adresse }}</td>
                                </tr>
                                <tr>
                                    <th>Ort</th>
                                    <td>{{ objekt.ort }}</td>
                                </tr>
                                <tr>
                                    <th>Plz</th>
                                    <td>{{ objekt.plz }}</td>
                                </tr>
                                <tr>
                                    <th>Main_mail</th>
                                    <td>{{ objekt.mainMail }}</td>
                                </tr>
                                <tr>
                                    <th>Website</th>
                                    <td>{{ objekt.website }}</td>
                                </tr>
                                <tr>
                                    <th>Telefon</th>
                                    <td>{{ objekt.telefon }}</td>
                                </tr>
                                <tr>
                                    <th>Fax</th>
                                    <td>{{ objekt.fax }}</td>
                                </tr>
                                <tr>
                                    <th>Bestellung_mail</th>
                                    <td>{{ objekt.bestellungMail }}</td>
                                </tr>
                                <tr>
                                    <th>Fibi_mail</th>
                                    <td>{{ objekt.fibiMail }}</td>
                                </tr>
                                <tr>
                                    <th>Ust_id</th>
                                    <td>{{ objekt.ustId }}</td>
                                </tr>
                                <tr>
                                    <th>Handelsregister</th>
                                    <td>{{ objekt.Handelsregister }}</td>
                                </tr>
                                <tr>
                                    <th>Amtsgericht</th>
                                    <td>{{ objekt.Amtsgericht }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <a class=" w-100 btn btn-primary " href="{{ path('app_objekt_edit', {'id': objekt.id}) }}">edit</a>
                    </blockquote>
                </div>
            </div> 
        </div>
        </div>
    </div>
    {{ include('objekt/_delete_form.html.twig') }}
   
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/modal.js') }}"></script>
    
    

{% endblock %}