src/Entity/Arbeitszeit.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ArbeitszeitRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArbeitszeitRepository::class)]
#[ApiResource]
class Arbeitszeit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $datum = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Eintrittszeit = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Austrittszeit = null;

    #[ORM\ManyToOne(inversedBy: 'arbeitszeits')]
    private ?Fehlzeiten $Fehlzeit = null;

    #[ORM\ManyToOne(inversedBy: 'arbeitszeits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getEintrittszeit(): ?\DateTimeInterface
    {
        return $this->Eintrittszeit;
    }

    public function setEintrittszeit(\DateTimeInterface $Eintrittszeit): self
    {
        $this->Eintrittszeit = $Eintrittszeit;

        return $this;
    }

    public function getAustrittszeit(): ?\DateTimeInterface
    {
        return $this->Austrittszeit;
    }

    public function setAustrittszeit(?\DateTimeInterface $Austrittszeit): self
    {
        $this->Austrittszeit = $Austrittszeit;

        return $this;
    }

    public function getFehlzeit(): ?Fehlzeiten
    {
        return $this->Fehlzeit;
    }

    public function setFehlzeit(?Fehlzeiten $Fehlzeit): self
    {
        $this->Fehlzeit = $Fehlzeit;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ArbeitszeitType.php
<?php

namespace App\Form;

use App\Entity\Arbeitszeit;
use App\Entity\Fehlzeiten;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArbeitszeitType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $formId = $options['form_id'];
        $builder
        ->add('form_id', HiddenType::class, [
            'mapped' => false,
            'data' => $options['form_id'], // Hier übergeben Sie die ID als Option
        ])
            ->add('datum', DateTimeType::class, [
                'attr' => ['style' => 'display:none;'],
                'label' => false,
            ])
            
            ->add('Eintrittszeit')
            ->add('Austrittszeit')
            ->add('Fehlzeit', EntityType::class,[
                'class' => Fehlzeiten::class,
                'attr' => ['style' => 'display:none;'],
                'label' => false,
            ])
            ->add('user', EntityType::class,[
                'class' => User::class,
                'attr' => ['style' => 'display:none;'],
                'label' => false,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Save',
                'attr' => [
                    'class' => 'btn btn-info',
                    'name' => 'my_form_id',
                    'value' => 'save', // Hier kannst du eine variable ID einsetzen
                ],
            ])
            ->add('delate', SubmitType::class, [
                'label' => 'delate',
                'attr' => [
                    'class' => 'btn btn-info',
                    'name' => 'my_form_id_delate',
                    'value' => 'delate', // Hier kannst du eine variable ID einsetzen
                ],
            ])
            ->add('newsave', SubmitType::class, [
                'label' => 'newsave',
                'attr' => [
                    'style' => 'display:none;',
                    'class' => 'btn btn-info',
                    'name' => 'my_form_id_delate',
                    'value' => 'newsave', // Hier kannst du eine variable ID einsetzen
                ],
            ])
        ;
        $builder->setAttribute('form_id', $formId);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Arbeitszeit::class,
            'form_id' => null,
        ]);
    }
}

src/Controller/ArbeitszeitController.php
<?php

namespace App\Controller;

use App\Entity\Arbeitszeit;
use App\Form\ArbeitszeitType;
use App\Repository\ArbeitszeitRepository;
use App\Repository\ContractDataRepository;
use App\Repository\DiensteRepository;
use App\Repository\FehlzeitenRepository;
use App\Repository\UserRepository;
use DateTime;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Time;

#[Route('/arbeitszeit')]        
class ArbeitszeitController extends AbstractController
{
    #[Route('/', name: 'app_arbeitszeit', methods: ['GET'])]
    public function index(ArbeitszeitRepository $arbeitszeitRepository): Response
    {
        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        $Arbeitszeit = $arbeitszeitRepository->findBy( ['user' => $user, 'Austrittszeit' => null ]);
      
        return $this->render('arbeitszeit/index.html.twig', [
            'user' => $user ,
            'Arbeitszeiten' => $Arbeitszeit ,

        ]);
    }
    #[Route('/checkIn', name: 'app_arbeitszeit_checkIn', methods: ['GET'])]
    public function checkIn(ManagerRegistry $doctrine): Response
    {
        
        $time = new DateTime(date("H:i:s"));
        $day = new DateTime(date("Y-m-d"));
        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        $Arbeitszeit = new Arbeitszeit();
        $Arbeitszeit->setUser($user);
        $Arbeitszeit->setEintrittszeit($time);
        $Arbeitszeit->setDatum($day);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($Arbeitszeit);
        $entityManager->flush();
        if ($entityManager->contains($Arbeitszeit)) {
            $datas = true;
        } else {
            $datas = false;
        }
        return new JsonResponse($datas);
    }
    #[Route('/checkOut', name: 'app_arbeitszeit_checkOut', methods: ['GET'])]
    public function checkOut(ArbeitszeitRepository $arbeitszeitRepository,ManagerRegistry $doctrine): Response
    {
        
        $time = new DateTime(date("H:i:s"));
        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        $Arbeitszeiten = $arbeitszeitRepository->findBy( ['user' => $user, 'Austrittszeit' => null ]);
        $Arbeitszeit = $Arbeitszeiten[0];
        $Arbeitszeit->setUser($user);
        $Arbeitszeit->setAustrittszeit($time);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($Arbeitszeit);
        $entityManager->flush();
        if ($entityManager->contains($Arbeitszeit)) {
            $datas = true;
        } else {
            $datas = false;
        }
        return new JsonResponse($datas);
    }
    #[Route('/amendment', name: 'app_arbeitszeit_amendment', methods: ['GET', 'POST'])]
    public function amendment(Request $request): Response
    {
        $data = $request->request->all();
        
        $kommen = $data['kommen'];
        $gehen = $data['gehen'];
        $day = $data['day'];
        $userId = $data['userId'];

        $jsonData = json_encode($data);

        $publicDirectory = $this->getParameter('kernel.project_dir') . '/public';
        $filename = sprintf('%s/data/dienstplan/aenerungsantrag_%s_%s.json', $publicDirectory, $day, $userId);

        file_put_contents($filename, $jsonData);
       
            $datas = true; 
         
        return new Response($datas);
    }
    #[Route('/ckeckin_api', name: 'app_arbeitszeit_ckeckin_api', methods: ['GET', 'POST'])]
    public function ckeckin_api(UserRepository $userRepository,ManagerRegistry $doctrine, ArbeitszeitRepository $arbeitszeitRepository): Response
    {   
        // API-Schlüssel
        $apiKey = 'geheimerKey';
        if (!isset($_SERVER['HTTP_ACCESSTOKEN']) || $_SERVER['HTTP_ACCESSTOKEN'] !== $apiKey) {
            header('HTTP/1.1 401 Unauthorized');
            die('Ungültiger API-Schlüssel');
        }
        $data = $_POST['data'];
        $data = json_decode($data);
        $time = new DateTime(date("H:i:s"));
        $user = $userRepository->find($data);
        $entityManager = $doctrine->getManager();
      
        if($user == null){
            $datas = ["status"=> false, 'message'=>'user ist nicht definiert'];
        }
        else{
            $Arbeitszeiten = $arbeitszeitRepository->findBy( ['user' => $user, 'Austrittszeit' => null ]);
            if(count($Arbeitszeiten)>1){
                $datas = ["status"=> false, 'message'=>'User ist mehrere mal eingcheckt'];
            }
            elseif(count($Arbeitszeiten)>0){
                $Arbeitszeiten = $arbeitszeitRepository->findBy( ['user' => $user, 'Austrittszeit' => null ]);
                $Arbeitszeit = $Arbeitszeiten[0];
                $Arbeitszeit->setUser($user);
                $Arbeitszeit->setAustrittszeit($time);
                $entityManager->persist($Arbeitszeit);
            }
            else{
                //Checkin
                $day = new DateTime(date("Y-m-d"));
                $Arbeitszeit = new Arbeitszeit();
                $Arbeitszeit->setUser($user);
                $Arbeitszeit->setEintrittszeit($time);
                $Arbeitszeit->setDatum($day);
                $entityManager->persist($Arbeitszeit);
            }
            //save und Check
            $entityManager->flush();
            if ($entityManager->contains($Arbeitszeit)) {
                $datas = $datas = ["status"=> true, 'message'=>'erfolgreich gespeichert'];
            } else {
                $datas = ["status"=> false, 'message'=>'fehler beim speichern'];
            }
        }
        return new JsonResponse($datas); 
    }
    #[Route('/opanamendment', name: 'app_arbeitszeit_opanamendment', methods: ['GET', 'POST'])]
    public function opanamendment(UserRepository $userRepository): Response
    {
        $publicDirectory = $this->getParameter('kernel.project_dir') . '/public';
        $path = sprintf('%s/data/dienstplan/', $publicDirectory);
        $files = glob($path . 'aenerungsantrag_*.json');
        $data = [];
        $count = 0;
        foreach ($files as $file) {
            $data[] = json_decode(file_get_contents($file), true);   
            $day = $data[$count]['day'];
            $userId = $data[$count]['userId'];  
            $user = $userRepository->find($userId);
            //dienste
            $dienste = $user->getDienste()->getValues();
            $array =[] ;
            foreach($dienste as $dienst){
                $tag = $dienst->getKommen()->format('Y-m-d');
                $kommen = $dienst->getKommen()->format('H:i');
                $gehen = $dienst->getGehen()->format('H:i');
                $dienstId = $dienst->getId();
                if($tag == $day){
                    $array[] = [
                        'kommen' => $kommen,
                        'gehen' => $gehen,
                        'dienstId' => $dienstId,
                    ];
                } 
            } 
            $data[$count]['dienst'] = $array;
            //Arbeitzzeiten
         
            $arbeitszeiten = $user->getArbeitszeits()->getValues();
            $array =[] ;
            foreach($arbeitszeiten as $arbeitszeit){
                
                $kommen = $arbeitszeit->getEintrittszeit()->format('H:i');
                if ($arbeitszeit->getAustrittszeit() !== null) {
                    $gehen = $arbeitszeit->getAustrittszeit()->format('H:i');
                } else {
                    $gehen = $arbeitszeit->getAustrittszeit();
                }
               
                $arbeitszeitId = $arbeitszeit->getId();
                $datum = $arbeitszeit->getDatum()->format('Y-m-d');
                if($arbeitszeit->getDatum()->format('Y-m-d') == $day){
                    $array[] = [
                        'datum' => $datum,
                        'kommen' => $kommen,
                        'gehen' => $gehen,
                        'arbeitszeitId' => $arbeitszeitId,
                    ];
                } 
            }
            $data[$count]['arbeitszeit'] = $array;
            $count ++;

        }
        $Company = $this->container->get('security.token_storage')->getToken()->getUser()->getCompany();
        
        $rool =$this->container->get('security.token_storage')->getToken()->getUser()->getRoles();
        if(in_array('ROLE_HR',$rool)){
            $users = $userRepository->findBy(['company' => $Company]);
            return $this->render('arbeitszeit/amendment.html.twig', [
                        'data' => $data ,
                        'users' => $users ,
            ]);    
        
        }else{
            return new JsonResponse('noroles');
        }
       
    }
    #[Route('/SaveAmendment', name: 'app_arbeitszeit_SaveAmendment', methods: ['GET', 'POST'])]
    public function SaveAmendment(Request $request, ManagerRegistry $doctrine,ArbeitszeitRepository $arbeitszeitRepository): Response
    {
        $data = $request->request;
        $id = $data->get('id');
        $kommen = new \DateTime($data->get('kommen'));
        $gehen = new \DateTime($data->get('gehen'));
        $Arbeitszzeit= $arbeitszeitRepository->find($id);
        $Arbeitszzeit->setEintrittszeit($kommen);
        $Arbeitszzeit->setAustrittszeit($gehen);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($Arbeitszzeit);
        $entityManager->flush();
        $day  = $kommen->format('Y-m-d');
        $userId =  $Arbeitszzeit->getUser()->getId();
        if ($entityManager->contains($Arbeitszzeit)) {
            

templates/arbeitszeit/amendment.html.twig
{% block body %}
    <h1>Amendment</h1>

    
        {% for item in data %}
            <div class="card text-center">
              
              <div class="card-body">
                
                 {% for user in users %}
              {% if user.id == item.userId %}
                <h4 class="card-title">{{ user.vorname}} {{ user.nachname}}</h4>
               {% endif %}
             {% endfor %}
              
             
             
        
             <h5> Lautdienstplan</h5>
             {% for dienst in item.dienst %}
           <p class="border border-info">{{ dienst.kommen}} - {{ dienst.gehen}}</p>
             {% endfor %}
            
            <h5>Ist Arbeitszeit</h5>
            <form id="save_amendment" type='POST'>
              <select class="form-control w-100 mb-2" name="id" id="">
                 {% for arbeitszeit in item.arbeitszeit %}
            <option value='{{ arbeitszeit.arbeitszeitId }}'>{{ arbeitszeit.kommen}} - {{ arbeitszeit.gehen}}</option>
             {% endfor %}
           
              </select>
              <h5> Änderungswunsch</h5>
            <div style='display:flex;'>
            <input name="kommen" id=""  class="form-control w-50 mb-2" type="time" value="{{ item.kommen }}"> 
            <input name="gehen" id="" class="form-control w-50 mb-2" type="time" value="{{ item.gehen }}">
            </div>
            <Button  id="save_amendment" class="btn btn-primary w-100"  role="button">wünsch übernehmen</Button></li>
           </form>
          </div>
            </div>  
        {% endfor %}
    
{% endblock %}

templates/arbeitszeit/arbeitszeitNew.html.twig
{% block body %}
<h5>Arbeitszeiten anlgen</h5>


<div id ='fehlzeit_add_show' >
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
</div>


{% endblock %}
{% block javascripts %}
   
 
  <script>
  function submitNewForm(event) { 
   
        event.preventDefault();
        var buttonValue = $(document.activeElement).val();
        var form = $(this);
        var data = $(this).serialize();
        $.ajax({
            type: "POST",
            url: "{{ path('app_user_arbeitszeiten_edit', {'id': user.id}) }}",
            data: data,
            dataType: "text",
            success: function(data) {
             //  location.reload();
             
             console.log("gespeichert");
            }
        });
  }
  $(document).ready(function(){
    
    $('#fehlzeiten_form').submit(submitNewForm);
  });

</script>
{% endblock %}

templates/arbeitszeit/edit.html.twig
{% block body %}
<h5>Arbeitszeiten</h5>
<table class='table'>
        <thead>
            <tr>
                <th>User</th>
                <th>Datum</th>
                <th>Kommen</th>
                <th>Gehen</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for arbeitszeit in arbeitszeiten %}
                {{ form_start(form[arbeitszeit.id])}}
                <tr>
                    <td><p style='margin-top: 0.4rem'>{{ arbeitszeit.user.vorname }}</p></td>
                    <td><p style='margin-top: 0.4rem'>{{ arbeitszeit.datum|date('d.m.Y') }}</p></td>
                      {% if arbeitszeit.fehlzeit is null %}
                    <td>{{ form_row(form[arbeitszeit.id].Eintrittszeit, {'label': false}) }}</td>
                    <td>{{ form_row(form[arbeitszeit.id].Austrittszeit, {'label': false}) }}</td>
                   {% else %}
                   <td colspan="2" class='nofieldset'><p style='margin-top: 0.4rem'>{{ arbeitszeit.fehlzeit.bezeichnung }}</p>
                 
                    {{ form_row(form[arbeitszeit.id].Eintrittszeit, {'label': false}) }}
                    {{ form_row(form[arbeitszeit.id].Austrittszeit, {'label': false}) }}
                     
                     </td>
                   {% endif  %} 
                        
                   
                    <td>
                    {{ form_widget(form[arbeitszeit.id].save, {'label': "save", 'attr': {'id': 'save-' ~ arbeitszeit.id, 'name': 'form_' ~ arbeitszeit.id}}) }}
                    {{ form_widget(form[arbeitszeit.id].delate, {'label': "delate", 'attr': {'id': 'delate-' ~ arbeitszeit.id, 'name': 'form_' ~ arbeitszeit.id}}) }}
                    </td>
                </tr>
               {{ form_end(form[arbeitszeit.id])}}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block javascripts %}
   
 
  <script>
  function submitForm(event) { 
    
        event.preventDefault();
        var buttonValue = $(document.activeElement).val();
        var form = $(this);
        var data = $(this).serialize() + '&buttonValue=' + buttonValue;
        $.ajax({
            type: "POST",
            url: "{{path('app_arbeitszeit_edit')}}",
            data: data,
            dataType: "text",
            success: function(data) {
             //  location.reload();
             console.log('gespeichert');
             if(buttonValue == 'delate'){
                form.next().hide();
             }
            }
        });
  }
  $(document).ready(function(){
    $('.mb-3').removeClass('mb-3');
    $('form[name="arbeitszeit"]').submit(submitForm);
    $('.nofieldset fieldset').hide();
  });
window.addEventListener('load', function() {
    // Finde alle delate-Buttons
    const delateButtons = document.querySelectorAll('#arbeitszeit_delate');
    
    // Füge jedem Button einen Event-Listener hinzu
    for (const button of delateButtons) {
        button.addEventListener('click', function(event) {
            // Zeige eine Bestätigungsmeldung an
            if (!confirm('Möchtest du diesen Eintrag wirklich löschen?')) {
                // Verhindere das Absenden des Formulars, wenn der Benutzer auf "Nein" klickt
                event.preventDefault();
            }
        });
    }
    


});
</script>
{% endblock %}

templates/arbeitszeit/index.html.twig
{% block body %}


<div class="example-wrapper">

{% if Arbeitszeiten|length > 0 %}
    {% for zeit in Arbeitszeiten %}
        <h5>CheckIn: {{ zeit.Eintrittszeit|date("H:i:s") }}</h5>
            <a name="" onclick="userCheckOut()" class="btn btn-info m-2" href="#" role="button">Logout</a><br>
            <a name="" onclick='openModal_Arbeitzzeit_aendern_beantragen({{ zeit.datum|date("U") }}, {{ zeit.user.id }})' class="btn m-2 btn-light" href="#" role="button">Vergessen zu Stempeln?</a> 
    {% endfor %} 
  
{% else %}
    <a name="" onclick="userCheckIn()" class="btn btn-info" href="#" role="button">Login</a>
{% endif %}

   
</div>
{% endblock %}

templates/arbeitszeit/new.html.twig
{% block body %}
<h5>Fehlzeiten</h5>
<button id ='fehlzeit_add_show_btn' type="button" class="btn btn-info mb-3" data-toggle="tooltip" data-placement="top" title=" Click um Fehlzeiten wie Urlaub und Krank zu erfassen">
    fehlzeit anlegen
</button>
<br>
<div id ='fehlzeit_add_show' style='display:none'>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
</div>
<button id ='fehlzeit_pv_show_btn' type="button" class="btn btn-info mb-3" data-toggle="tooltip" data-placement="top" title=" Click um Fehlzeiten wie Urlaub und Krank zu sehen">
    fehlzeit übersicht
</button>
<div id='fehlzeit_pv_show' style='display:none'>
<table class="table">
    <thead>
        <tr>
            <th>Datum</th>
            <th>Fehlzeit</th>
            <th>aktion</th>
        </tr>
    </thead>
    <tbody>
    {% for arbeitszeit in arbeitszeiten %}
        <tr>
            <td >{{arbeitszeit.datum|date('Y-m-d')}}</td>
            <td>{{arbeitszeit.fehlzeit.bezeichnung}}</td>
            <td></td>
        </tr>
      {% endfor %} 
    </tbody>
</table>

</div>
{% endblock %}